import { useEffect, useState } from "react";
import { Check, Copy, Heart, LoaderCircle, LogIn, LogOut, Pencil, Plus, RefreshCw, Trash2, UserRound, X } from "lucide-react";
import { validateUsername } from "../services/accounts/AccountValidator";
import { useAccountStore } from "../stores/accountStore";
import type { Account } from "../services/accounts/OfflineAccount";
import { resolveAvatarSrc } from "../services/accounts/OfflineAccount";

export default function Accounts() {
  const store = useAccountStore();
  const [offlineModal, setOfflineModal] = useState(false);
  const [elyModal, setElyModal] = useState(false);
  const [username, setUsername] = useState("");
  const [elyUsername, setElyUsername] = useState("");
  const [elyPassword, setElyPassword] = useState("");
  const [editing, setEditing] = useState<Account | null>(null);
  const [formError, setFormError] = useState("");
  useEffect(() => { void store.loadAccounts(); }, [store.loadAccounts]);
  const openOffline = (account?: Account) => { setEditing(account ?? null); setUsername(account?.username ?? ""); setFormError(""); setOfflineModal(true); };
  const startMicrosoftLogin = () => { void store.loginMicrosoft().catch(() => { /* store exposes the error */ }); };
  const saveOffline = async (event: React.FormEvent) => {
    event.preventDefault();
    const validation = validateUsername(username);
    if (validation) { setFormError(validation); return; }
    if (editing) await store.updateAccount({ ...editing, username, skinPath: `https://mc-heads.net/avatar/${encodeURIComponent(username)}` });
    else await store.createAccount(username);
    setOfflineModal(false);
  };
  return <div className="accounts-page">
    <div className="page-title accounts-header"><div><span className="eyebrow"><UserRound size={13} /> ACCOUNTS</span><h1>Accounts</h1><p>Manage Offline and Ely.by profiles for Minecraft.</p></div><div className="account-header-actions"><button className="secondary-button" onClick={startMicrosoftLogin}><LogIn size={15} /> Sign in with Microsoft</button><button className="secondary-button" onClick={() => setElyModal(true)}><LogIn size={15} /> Sign in with Ely.by</button><button className="primary-button" onClick={() => openOffline()}><Plus size={15} /> Create Offline</button></div></div>
    {store.error && <div className="java-error">{store.error.replace("Error: ", "")}</div>}
    {store.loading && !store.accounts.length ? <div className="instance-loading">Loading accounts…</div> : store.accounts.length ? <div className="accounts-grid">{store.accounts.map((account) => <article className={`account-card ${store.selectedAccount?.id === account.id ? "selected-account" : ""}`} key={account.id}><div className="account-card-top"><img src={resolveAvatarSrc(account.skinPath) || `https://mc-heads.net/avatar/${encodeURIComponent(account.username)}`} alt={`${account.username} avatar`} /><button className={`favorite-button ${account.favorite ? "favorite" : ""}`} onClick={() => void store.toggleFavorite(account)} title="Favorite"><Heart size={16} fill={account.favorite ? "currentColor" : "none"} /></button></div><div className="account-body"><div className="account-title"><h2>{account.username}</h2>{store.selectedAccount?.id === account.id && <span className="default-pill"><Check size={11} /> ACTIVE</span>}</div><p className="account-type">{account.type} account{account.email ? ` · ${account.email}` : ""}</p><code>{account.uuid}</code><div className="account-actions"><button className="primary-button" onClick={() => store.selectAccount(account)}><Check size={14} /> Select</button>{account.type === "Offline" ? <button title="Edit" onClick={() => openOffline(account)}><Pencil size={14} /></button> : <><button title="Refresh token" onClick={() => void (account.type === "Microsoft" ? store.refreshMicrosoft(account) : store.refreshElyBy(account))} disabled={store.loading}>{store.loading ? <LoaderCircle className="spin" size={14} /> : <RefreshCw size={14} />}</button><button title="Logout" onClick={() => void (account.type === "Microsoft" ? store.logoutMicrosoft(account) : store.logoutElyBy(account))}><LogOut size={14} /></button></>}<button className="danger-action" title="Delete" onClick={() => { if (window.confirm(`Delete ${account.username}?`)) void store.deleteAccount(account.id); }}><Trash2 size={14} /></button></div></div></article>)}</div> : <div className="instances-empty"><div className="empty-icon"><UserRound size={24} /></div><span className="eyebrow">ACCOUNTS</span><h2>No accounts yet</h2><p>Create an offline profile, or sign in with Microsoft or Ely.by.</p><div className="account-header-actions"><button className="primary-button" onClick={startMicrosoftLogin}><LogIn size={15} /> Sign in with Microsoft</button><button className="secondary-button" onClick={() => setElyModal(true)}><LogIn size={15} /> Sign in with Ely.by</button></div></div>}
    {store.msDeviceCode && <div className="modal-backdrop" onClick={() => store.cancelMicrosoftLogin()}><div className="modal-card compact-modal" onClick={(event) => event.stopPropagation()}><button type="button" className="modal-close" onClick={() => store.cancelMicrosoftLogin()}><X size={17} /></button><span className="eyebrow">MICROSOFT ACCOUNT</span><h2>Sign in with Microsoft</h2><p className="account-form-note">Open the link below, enter the code, and sign in with your Microsoft account. This window will finish automatically.</p><a href={store.msDeviceCode.verificationUri} target="_blank" rel="noreferrer" className="secondary-button modal-submit" style={{ textDecoration: "none", justifyContent: "center" }}>{store.msDeviceCode.verificationUri}</a><div className="account-form-note" style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, fontSize: 22, fontWeight: 700, letterSpacing: 2, margin: "12px 0" }}>{store.msDeviceCode.userCode}<button type="button" title="Copy code" onClick={() => void navigator.clipboard.writeText(store.msDeviceCode!.userCode)}><Copy size={14} /></button></div><div className="account-form-note" style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8 }}><LoaderCircle className="spin" size={14} /> Waiting for sign-in…</div></div></div>}
    {elyModal && <div className="modal-backdrop" onClick={() => setElyModal(false)}><form className="modal-card compact-modal" onSubmit={async (event) => { event.preventDefault(); try { await store.loginElyBy(elyUsername, elyPassword); setElyPassword(""); setElyModal(false); } catch { /* store exposes the error */ } }} onClick={(event) => event.stopPropagation()}><button type="button" className="modal-close" onClick={() => setElyModal(false)}><X size={17} /></button><span className="eyebrow">ELY.BY ACCOUNT</span><h2>Sign in with Ely.by</h2><label>Email or username<input autoFocus value={elyUsername} onChange={(event) => setElyUsername(event.target.value)} required /></label><label>Password<input type="password" value={elyPassword} onChange={(event) => setElyPassword(event.target.value)} required /></label><p className="account-form-note">Your password is sent only to Ely.by and is never stored by the launcher.</p><button className="primary-button modal-submit" type="submit" disabled={store.loading}><LogIn size={15} /> Sign in</button></form></div>}
    {offlineModal && <div className="modal-backdrop" onClick={() => setOfflineModal(false)}><form className="modal-card compact-modal" onSubmit={saveOffline} onClick={(event) => event.stopPropagation()}><button type="button" className="modal-close" onClick={() => setOfflineModal(false)}><X size={17} /></button><span className="eyebrow">{editing ? "EDIT PROFILE" : "NEW PROFILE"}</span><h2>{editing ? "Edit account" : "Create offline account"}</h2><label>Username<input autoFocus value={username} onChange={(event) => { setUsername(event.target.value); setFormError(""); }} maxLength={16} required /></label>{formError && <div className="version-error">{formError}</div>}<button className="primary-button modal-submit" type="submit"><Check size={15} /> Save Account</button></form></div>}
  </div>;
}